# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7868c7e3f9d5e9ab2b15212c29b19d287965517e962f622c228069238bdbffbc9b2bf0f9e627312107fad2b47d9d80c1d99419861d3d4814a26c0b6d032aab13

test:
  secret_key_base: ce7d17f4163906ac06bac48573daab84b3b9cea48fbb54c4c7eaeec44bff0849ef166789d78c3b8ef3291bc9e7b2b765e2da5ab360018d859f4d0f01fc88e51f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
